package v1alpha1

import (
	"k8s.io/apimachinery/pkg/conversion"
	"k8s.io/controller-manager/app/options"
	"k8s.io/kube-controller-manager/config/v1alpha1"
)

// Important! The public back-and-forth conversion functions for the types in this generic
// package with ComponentConfig types need to be manually exposed like this in order for
// other packages that reference this package to be able to call these conversion functions
// in an autogenerated manner.
// TODO: Fix the bug in conversion-gen so it automatically discovers these Convert_* functions
// in autogenerated code as well.

// Convert_v1alpha1_GenericControllerManagerConfiguration_To_options_GenericControllerManagerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_GenericControllerManagerConfiguration_To_options_GenericControllerManagerConfiguration(in *v1alpha1.GenericControllerManagerConfiguration, out *options.GenericControllerManagerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_GenericControllerManagerConfiguration_To_options_GenericControllerManagerConfiguration(in, out, s)
}

// Convert_options_GenericControllerManagerConfiguration_To_v1alpha1_GenericControllerManagerConfiguration is an autogenerated conversion function.
func Convert_options_GenericControllerManagerConfiguration_To_v1alpha1_GenericControllerManagerConfiguration(in *options.GenericControllerManagerConfiguration, out *v1alpha1.GenericControllerManagerConfiguration, s conversion.Scope) error {
	return autoConvert_options_GenericControllerManagerConfiguration_To_v1alpha1_GenericControllerManagerConfiguration(in, out, s)
}

// Convert_v1alpha1_KubeCloudSharedConfiguration_To_options_KubeCloudSharedConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_KubeCloudSharedConfiguration_To_options_KubeCloudSharedConfiguration(in *v1alpha1.KubeCloudSharedConfiguration, out *options.KubeCloudSharedConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeCloudSharedConfiguration_To_options_KubeCloudSharedConfiguration(in, out, s)
}

// Convert_config_KubeCloudSharedConfiguration_To_v1alpha1_KubeCloudSharedConfiguration is an autogenerated conversion function.
func Convert_options_KubeCloudSharedConfiguration_To_v1alpha1_KubeCloudSharedConfiguration(in *options.KubeCloudSharedConfiguration, out *v1alpha1.KubeCloudSharedConfiguration, s conversion.Scope) error {
	return autoConvert_options_KubeCloudSharedConfiguration_To_v1alpha1_KubeCloudSharedConfiguration(in, out, s)
}

// Convert_v1alpha1_ServiceControllerConfiguration_To_options_ServiceControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ServiceControllerConfiguration_To_options_ServiceControllerConfiguration(in *v1alpha1.ServiceControllerConfiguration, out *options.ServiceControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceControllerConfiguration_To_options_ServiceControllerConfiguration(in, out, s)
}

// Convert_options_ServiceControllerConfiguration_To_v1alpha1_ServiceControllerConfiguration is an autogenerated conversion function.
func Convert_options_ServiceControllerConfiguration_To_v1alpha1_ServiceControllerConfiguration(in *options.ServiceControllerConfiguration, out *v1alpha1.ServiceControllerConfiguration, s conversion.Scope) error {
	return autoConvert_options_ServiceControllerConfiguration_To_v1alpha1_ServiceControllerConfiguration(in, out, s)
}