// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package options

import (
	config "k8s.io/component-base/config"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderConfiguration) DeepCopyInto(out *CloudProviderConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderConfiguration.
func (in *CloudProviderConfiguration) DeepCopy() *CloudProviderConfiguration {
	if in == nil {
		return nil
	}
	out := new(CloudProviderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderOptions) DeepCopyInto(out *CloudProviderOptions) {
	*out = *in
	if in.CloudProviderConfiguration != nil {
		in, out := &in.CloudProviderConfiguration, &out.CloudProviderConfiguration
		*out = new(CloudProviderConfiguration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderOptions.
func (in *CloudProviderOptions) DeepCopy() *CloudProviderOptions {
	if in == nil {
		return nil
	}
	out := new(CloudProviderOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebuggingOptions) DeepCopyInto(out *DebuggingOptions) {
	*out = *in
	if in.DebuggingConfiguration != nil {
		in, out := &in.DebuggingConfiguration, &out.DebuggingConfiguration
		*out = new(config.DebuggingConfiguration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebuggingOptions.
func (in *DebuggingOptions) DeepCopy() *DebuggingOptions {
	if in == nil {
		return nil
	}
	out := new(DebuggingOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericControllerManagerConfiguration) DeepCopyInto(out *GenericControllerManagerConfiguration) {
	*out = *in
	out.MinResyncPeriod = in.MinResyncPeriod
	out.ClientConnection = in.ClientConnection
	out.ControllerStartInterval = in.ControllerStartInterval
	out.LeaderElection = in.LeaderElection
	if in.Controllers != nil {
		in, out := &in.Controllers, &out.Controllers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Debugging = in.Debugging
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericControllerManagerConfiguration.
func (in *GenericControllerManagerConfiguration) DeepCopy() *GenericControllerManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(GenericControllerManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericControllerManagerConfigurationOptions) DeepCopyInto(out *GenericControllerManagerConfigurationOptions) {
	*out = *in
	if in.GenericControllerManagerConfiguration != nil {
		in, out := &in.GenericControllerManagerConfiguration, &out.GenericControllerManagerConfiguration
		*out = new(GenericControllerManagerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Debugging != nil {
		in, out := &in.Debugging, &out.Debugging
		*out = new(DebuggingOptions)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericControllerManagerConfigurationOptions.
func (in *GenericControllerManagerConfigurationOptions) DeepCopy() *GenericControllerManagerConfigurationOptions {
	if in == nil {
		return nil
	}
	out := new(GenericControllerManagerConfigurationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeCloudSharedConfiguration) DeepCopyInto(out *KubeCloudSharedConfiguration) {
	*out = *in
	out.CloudProvider = in.CloudProvider
	out.RouteReconciliationPeriod = in.RouteReconciliationPeriod
	out.NodeMonitorPeriod = in.NodeMonitorPeriod
	out.NodeSyncPeriod = in.NodeSyncPeriod
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeCloudSharedConfiguration.
func (in *KubeCloudSharedConfiguration) DeepCopy() *KubeCloudSharedConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubeCloudSharedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeCloudSharedOptions) DeepCopyInto(out *KubeCloudSharedOptions) {
	*out = *in
	if in.KubeCloudSharedConfiguration != nil {
		in, out := &in.KubeCloudSharedConfiguration, &out.KubeCloudSharedConfiguration
		*out = new(KubeCloudSharedConfiguration)
		**out = **in
	}
	if in.CloudProvider != nil {
		in, out := &in.CloudProvider, &out.CloudProvider
		*out = new(CloudProviderOptions)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeCloudSharedOptions.
func (in *KubeCloudSharedOptions) DeepCopy() *KubeCloudSharedOptions {
	if in == nil {
		return nil
	}
	out := new(KubeCloudSharedOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceControllerConfiguration) DeepCopyInto(out *ServiceControllerConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceControllerConfiguration.
func (in *ServiceControllerConfiguration) DeepCopy() *ServiceControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceControllerOptions) DeepCopyInto(out *ServiceControllerOptions) {
	*out = *in
	if in.ServiceControllerConfiguration != nil {
		in, out := &in.ServiceControllerConfiguration, &out.ServiceControllerConfiguration
		*out = new(ServiceControllerConfiguration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceControllerOptions.
func (in *ServiceControllerOptions) DeepCopy() *ServiceControllerOptions {
	if in == nil {
		return nil
	}
	out := new(ServiceControllerOptions)
	in.DeepCopyInto(out)
	return out
}
